server:
  port: 8081

spring:
  application:
    name: stock-service
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
